version: 2

models:
  - name: join_table1
    description: This table contains orders and customers :)
    
  - name: table2
    description: This table contains super new id :)

  - name: customers
    description: This table contains customers :)

    columns:
      - name: '"id"'
        description: This is a unique identifier for the event
        tests:
          - unique:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
          - not_null:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
      - name: '"first_name"'
        description: This is a name
        tests:
          - unique:
              config:
                severity: error
                error_if: ">100"
                warn_if: ">5"

  - name: orders
    description: This table contains orders :)

    columns:
      - name: '"id"'
        description: This is a unique identifier for the event
        tests:
          - unique:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
          - not_null:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
