version: 2

models:
  - name: join_table1
    description: This table contains orders and customers :)
    
  - name: table2
    description: This table contains super new id :)

  - name: customers
    description: This table contains customers :)

    columns:
      - name: id
        description: This is a unique identifier for the event

  - name: orders
    description: This table contains orders :)
